# Machine Learning Assignment 2 — Dry Bean Classification

This notebook trains the five classification models explicitly named in the assignment PDF and saves the artifacts required by the Streamlit app.

In [1]:
# Install only if your environment does not already have these packages
# !pip install -r requirements.txt

In [2]:
from pathlib import Path
import sys
PROJECT_ROOT = Path.cwd()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
print('Project root:', PROJECT_ROOT)

Project root: C:\ML_Assignment_2_DryBean

In [3]:
from ml_utils import load_dry_bean_dataset, FEATURE_COLUMNS, TARGET_COLUMN
df = load_dry_bean_dataset(PROJECT_ROOT)
print('Dataset shape:', df.shape)
print('Number of features:', len(FEATURE_COLUMNS))
print('Target:', TARGET_COLUMN)
display(df.head())
display(df[TARGET_COLUMN].value_counts())

Dataset shape: (13611, 17)
Number of features: 16
Target: Class

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent,Solidity,roundness,Compactness,ShapeFactor1,ShapeFactor2,ShapeFactor3,ShapeFactor4,Class
0,28395,610.291,208.178117,173.888747,1.197191,0.549812,28715,190.141097,0.763923,0.988856,0.958027,0.913358,0.007332,0.003147,0.834222,0.998724,SEKER
1,28734,638.018,200.524796,182.734419,1.097356,0.411785,29172,191.272751,0.783968,0.984986,0.887034,0.953861,0.006979,0.003564,0.909851,0.998430,SEKER
2,29380,624.110,212.826130,175.931143,1.209713,0.562727,29690,193.410904,0.778113,0.989559,0.947849,0.908774,0.007244,0.003048,0.825871,0.999066,SEKER
3,30008,645.884,210.557999,182.516516,1.153638,0.498616,30724,195.467062,0.782681,0.976696,0.903936,0.928329,0.007017,0.003215,0.861794,0.994199,SEKER
4,30140,620.134,201.847882,190.279279,1.060798,0.333680,30417,195.896503,0.773098,0.990893,0.984877,0.970516,0.006697,0.003665,0.941900,0.999166,SEKER

Class
DERMASON    3546
SIRA        2636
SEKER       2027
HOROZ       1928
CALI        1630
BARBUNYA    1322
BOMBAY       522
Name: count, dtype: int64

## Train all models and generate the required artifacts

The training function performs the 80/20 stratified split, trains all models, calculates Accuracy, AUC, Precision, Recall, F1 and MCC, saves all model files, generates `test_data.csv`, and creates the comparison table.

In [4]:
from model.train_models import main
main()

========================================================================
ML Assignment 2 - Dry Bean Classification
========================================================================

[1/7] Loading dataset...
Dataset shape          : (13611, 17)
Input features         : 16
Target column          : Class
Number of classes      : 7
Missing rows removed   : 0

Class distribution:
Class
BARBUNYA    1322
BOMBAY       522
CALI        1630
DERMASON    3546
HOROZ       1928
SEKER       2027
SIRA        2636
Name: count, dtype: int64

[2/7] Preparing X and y...
Encoded classes:
  0 -> BARBUNYA
  1 -> BOMBAY
  2 -> CALI
  3 -> DERMASON
  4 -> HOROZ
  5 -> SEKER
  6 -> SIRA

[3/7] Creating stratified train/test split (80/20)...
Training samples       : 10888
Test samples           : 2723
Saved test data        : test_data.csv

[4/7] Saving label encoder...
Saved                  : model\label_encoder.pkl

[5/7] Training and evaluating models...

--- Logistic Regression ---

Accuracy  : 0.9207
AUC       : 0.9934
Precision : 0.9215
Recall    : 0.9207
F1        : 0.9209
MCC       : 0.9042
Saved model: model\logistic_regression.pkl

--- Decision Tree ---
Accuracy  : 0.8917
AUC       : 0.9330
Precision : 0.8912
Recall    : 0.8917
F1        : 0.8913
MCC       : 0.8691
Saved model: model\decision_tree.pkl

--- kNN ---

Accuracy  : 0.9166
AUC       : 0.9812
Precision : 0.9174
Recall    : 0.9166
F1        : 0.9168
MCC       : 0.8992
Saved model: model\knn.pkl

--- Naive Bayes ---
Accuracy  : 0.8979
AUC       : 0.9902
Precision : 0.9007
Recall    : 0.8979
F1        : 0.8981
MCC       : 0.8773
Saved model: model\naive_bayes.pkl

--- Random Forest ---

Accuracy  : 0.9232
AUC       : 0.9921
Precision : 0.9233
Recall    : 0.9232
F1        : 0.9232
MCC       : 0.9072
Saved model: model\random_forest.pkl

[6/7] Creating comparison table...

      ML Model Name  Accuracy    AUC  Precision  Recall     F1    MCC
Logistic Regression    0.9207 0.9934     0.9215  0.9207 0.9209 0.9042
      Decision Tree    0.8917 0.9330     0.8912  0.8917 0.8913 0.8691
                kNN    0.9166 0.9812     0.9174  0.9166 0.9168 0.8992
        Naive Bayes    0.8979 0.9902     0.9007  0.8979 0.8981 0.8773
      Random Forest    0.9232 0.9921     0.9233  0.9232 0.9232 0.9072

Saved comparison table : model_comparison.csv

[7/7] Selecting overall winner...
Overall winner by weighted F1: Random Forest

Training completed successfully.

Next command:
  streamlit run app.py

In [5]:
import pandas as pd
comparison = pd.read_csv(PROJECT_ROOT / 'model_comparison.csv')
display(comparison)

         ML Model Name  Accuracy     AUC  Precision  Recall      F1     MCC
0  Logistic Regression    0.9207  0.9934     0.9215  0.9207  0.9209  0.9042
1        Decision Tree    0.8917  0.9330     0.8912  0.8917  0.8913  0.8691
2                  kNN    0.9166  0.9812     0.9174  0.9166  0.9168  0.8992
3          Naive Bayes    0.8979  0.9902     0.9007  0.8979  0.8981  0.8773
4        Random Forest    0.9232  0.9921     0.9233  0.9232  0.9232  0.9072

## Next Step

After the training completes successfully, run:

```bash
streamlit run app.py
```

Use the generated `test_data.csv` in the Streamlit app and capture the required BITS Virtual Lab screenshot for the final PDF.